service: cloudx-course-product-service
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs16.x
  stage: dev
  region: eu-west-1
  iam:
    role:
      statements:
        - Effect: Allow
          Action: 
            - sns:Publish
          Resource: 
            Ref: SNSProductsTopic

resources:
  Resources:
    SQSProductsQueue:
      Type: AWS::SQS::Queue
      Properties:
        QueueName: cloudx-course-product-service-queue
    SNSProductsTopic:
      Type: AWS::SNS::Topic
      Properties:
        TopicName: cloudx-course-product-service-sns-topic
    SNSProductsImportSubscription:
      Type: AWS::SNS::Subscription
      Properties: 
        Endpoint: user@email.com
        Protocol: email
        TopicArn:
          Ref: SNSProductsTopic
    SNSProductsImportErrorSubscription:
      Type: AWS::SNS::Subscription
      Properties: 
        Endpoint: user@email.com
        Protocol: email
        FilterPolicyScope: MessageBody
        FilterPolicy:
          errors:
            - true
        TopicArn:
          Ref: SNSProductsTopic

plugins:
  - serverless-auto-swagger
  - serverless-webpack
  
custom:
  webpack:
    webpackConfig: 'webpack.config.js' 
  autoswagger:
    title: 'Product Service'

functions:
  catalogBatchProcess:
    handler: src/handlers/catalogBatchProcess.main
    events:
      - sqs:
          batchSize: 5
          arn:
            Fn::GetAtt:
              - SQSProductsQueue
              - Arn
  getProductsList:
    handler: src/handlers/getProductsList.main
    events:
      - http:
          path: products
          method: get
          cors: true
          swaggerTags: ['product service']
  getProductById:
    handler: src/handlers/getProductById.main
    events:
      - http:
          path: products/{productId}
          method: get
          cors: true
          swaggerTags: ['product service']
  createProduct:
    handler: src/handlers/createProduct.main
    events:
      - http:
          path: products
          method: post
          cors: true
          swaggerTags: ['product service']