service: cloudx-course-product-service
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs16.x
  stage: dev
  region: eu-west-1

plugins:
  - serverless-auto-swagger
  - serverless-webpack
  
custom:
  webpack:
    webpackConfig: 'webpack.config.js' 
  autoswagger:
    title: 'Product Service'

functions:
  getProductsList:
    handler: src/handlers/getProductsList.main
    events:
      - http:
          path: products
          method: get
          cors: true
          swaggerTags: ['product service']
  getProductById:
    handler: src/handlers/getProductById.main
    events:
      - http:
          path: products/{productId}
          method: get
          cors: true
          swaggerTags: ['product service']
  createProduct:
    handler: src/handlers/createProduct.main
    events:
      - http:
          path: products
          method: post
          cors: true
          swaggerTags: ['product service']