service: cloudx-course-authorization-service
frameworkVersion: "3"

provider:
  name: aws
  runtime: nodejs16.x
  stage: dev
  region: eu-west-1

plugins:
  - serverless-webpack
  - serverless-dotenv-plugin

custom:
  webpack:
    webpackConfig: "webpack.config.js"

functions:
  basicAuthorizer:
    handler: src/handlers/basicAuthorizer.main
